// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test-3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test-3', async function() {
    await driver.get("https://www.power.fi/")
    await driver.manage().window().setRect({ width: 788, height: 890 })
    await driver.findElement(By.css(".ng-tns-c150-3 > .search-input")).click()
    await driver.executeScript("window.scrollTo(0,375.3333435058594)")
    await driver.executeScript("window.scrollTo(0,800)")
    await driver.findElement(By.css(".ng-tns-c150-3 > .search-input")).sendKeys("iphone 12")
    await driver.findElement(By.css(".search-pages > .ng-tns-c164-2:nth-child(3) > font > font")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".btn-row:nth-child(3) font > font")).click()
    await driver.executeScript("window.scrollTo(0,8480)")
    await driver.findElement(By.css("#product-073686555 .swiper-slide:nth-child(1) .bold:nth-child(1) > font:nth-child(1) > font:nth-child(1)")).click()
    await driver.executeScript("window.scrollTo(0,3.3333332538604736)")
    await driver.executeScript("window.scrollTo(0,230)")
    await driver.findElement(By.css(".btn-mega")).click()
    {
      const element = await driver.findElement(By.css(".btn > .ng-star-inserted > font > font"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
